name: Backend

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.x', '7.x' ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release -r linux-x64 --no-build --no-restore --output ./publish
        working-directory: CorePlugin.Plugin
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Plugin (NET ${{ matrix.dotnet-version }})
          path: ./CorePlugin.Plugin/publish
