name: Frontend

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
        # currently disabled because headless-chrome is not setup yet
#      - name: Test
#        run: yarn test
